print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *   *")
print("  *****")
#mi solucion
print()
print("Mi solucion")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *   *\n  *****\n")
print()
print("Doble de grande")
print("        *\n       * *\n      *   *\n     *     *\n    *       *\n   *         *\n  *           *\n *             *\n******     ******\n     *     *\n     *     *\n     *     *\n     *     *\n     *     *\n     *     *\n     *******\n")
print()
print("Doble de grande y duplicado")
print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("******     ******"*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *******     "*2)
